theme: jekyll-theme-cayman

title: "Universes in Rocks"

nav:
  - title: "Home"
    url: "/"
  - title: "About"
    url: "/about"
  - title: "Research"
    url: "/research"
  - title: "Gallery"
    url: "/gallery"
  - title: "Contact"
    url: "/contact"